import { Worker, Job } from 'bullmq'
import { connection } from './redis'
import { ORDER_QUEUE_NAME } from './OrderQueue'
import { connectionManager } from '../sysbot/ConnectionManager'
import { discordBridge } from '../sysbot/DiscordBridge'
import { buildShowdownText } from '../lib/showdownBuilder'
import { PokemonBuildPayload } from '../lib/order-types'

/**
 * Worker that processes incoming web orders.
 * It continually runs in the background.
 */
export const orderWorker = new Worker(
  ORDER_QUEUE_NAME,
  async (job: Job) => {
    const { orderId, gameVersion, payload, tradeCode } = job.data

    console.log(`[OrderWorker] Processing order ${orderId} for ${gameVersion}`)

    // 1. Look for an available SysBot for this game version
    const bot = connectionManager.getAvailableBot(gameVersion)

    if (!bot) {
      console.log(`[OrderWorker] No idle bot found for ${gameVersion}. Re-queueing order ${orderId}...`)
      throw new Error(`No available bot for ${gameVersion}`)
    }

    // 2. Claim the bot
    bot.status = 'TRADING'
    // Use the trade code generated by the web frontend (ignoring the simulator's default code)
    const botTradeCode = tradeCode || bot.tradeCode
    console.log(`[OrderWorker] ℹ️  User must enter code ${botTradeCode} on their Nintendo Switch`)

    try {
      console.log(`[OrderWorker] Bot ${bot.id} assigned to order ${orderId}`)

      // 3. Generate and upload .pk9 files for the entire team
      const team = payload as PokemonBuildPayload[]
      const uploadedFiles: string[] = []

      for (let i = 0; i < team.length; i++) {
        const pokemon = team[i]
        try {
          // Convert payload to Showdown text directly using our builder
          const showdownText = buildShowdownText(pokemon, gameVersion)

          // Send to Discord via the selfbot bridge, passing the trade code
          const success = await discordBridge.sendTradeCommand(showdownText, botTradeCode)
          
          if (!success) {
            throw new Error(`DiscordBridge failed to send command for ${pokemon.species}. Please ensure the bridge is connected and the channel ID is valid.`)
          }
          
          uploadedFiles.push(`Sent via Discord: ${pokemon.species}`)
          
        } catch (err) {
          console.error(`[OrderWorker] Failed to process ${pokemon.species} in order ${orderId}:`, err)
          throw err // BullMQ will retry or fail the job
        }
      }

      // 6. Free the bot after the trade window (SysBot will read and clear the file)
      setTimeout(() => {
        if (bot.status === 'TRADING') {
          bot.status = 'IDLE'
          console.log(`[OrderWorker] Bot ${bot.id} returned to IDLE`)
        }
      }, 30000) // 30 seconds – enough time for SysBot to pick up and trade

      return { success: true, botId: bot.id, uploadedFiles }
    } catch (error) {
      bot.status = 'IDLE'
      throw error
    }
  },
  {
    connection,
    concurrency: 5,
  }
)

orderWorker.on('completed', (job) => {
  console.log(`[OrderWorker] ✅ Order ${job.id} was delivered successfully.`)
})

orderWorker.on('failed', (job, err) => {
  console.log(`[OrderWorker] ❌ Order ${job?.id} failed (will retry): ${err.message}`)
})

